### ISSUE TITLE
이것이 알고리즘 테스트다 3강 Greedy

### ISSUE THREAD

**Issue by hryeong66** [hryeong66/Algorithm#1]
## 📌  Feature Issue

3강 그리디 공부하고 문제풀기

## 📝  To-do

- [ ] 책의 문제 3가지 풀기 
- [ ] 추가 그리디 문제 풀기
- [ ] Swift로 문제 풀어보기
